default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :tests do
      run_tests(workspace: "Article.xcworkspace",
             scheme: "Article")
    end
end

platform :ios do
   desc "Runs all the tests"
   lane :slack_message do
	puts "STUFF: #{ENV['API_TOKEN']}"
      	puts "TEST KEY: #{ENV['TEST_KEY']}"
       slack(
           message: "App successfully uploaded to iTunesConnect.",
           success: true,
           slack_url: "#{ENV['SLACK_INCOMING_WEBHOOK']}"
       )
   end
end

