default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :tests do
      puts "STUFF: #{ENV['API_TOKEN']}"
      puts "TEST KEY: #{ENV['TEST_KEY']}"
    end
end

platform :ios do
   desc "Runs all the tests"
   lane :slack_message do
       slack(
           message: "App successfully uploaded to iTunesConnect.",
           success: true,
           slack_url: "#{ENV['SLACK_INCOMING_WEBHOOK']"
       )
   end
end

