name: CI

on: [push]

    

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - run: pod install
    - name: Do Something strange
      run: |
          for FILE in $(grep -Ril "https://github.com/onevcat/Kingfisher.git" .); do
          sed -i '' "s/https:\/\/github.com\/onevcat/Kingfisher.git/https:\/\/${GITHUB_PAT}@github.com\/onevcat/Kingfisher.git/g" ${FILE}
          done
    - name: Update known_hosts
      run: |
        cd ~/.ssh
        ls
        cat known_hosts
        for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
    - name: Build
      run: xcodebuild test -workspace 'The Guardian.xcworkspace' -scheme 'The Guardian' -configuration 'Debug' -destination 'platform=iOS Simulator,name=iPhone XS,OS=13'
