on:
  pull_request:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Please select the build configuration
        options:
        - dev
        - staging

jobs:
  build:
    name: Deploy
    runs-on: macOS-latest
      
    steps:
    
      - name: Run dev action
        if: ${{ (github.event.inputs.choice == '') || (github.event.inputs.choice == 'dev') }}
        run: echo "dev build"

      - name: Run staging action
        if: ${{ github.event.inputs.choice == 'staging' }}
        run: echo "staging build"
