name: build

on:
  pull_request:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Please select the build configuration
        options:
        - dev
        - staging

jobs:
  build:
    name: Deploy
    runs-on: macOS-latest
      
    steps:
    
      - name: Print selected choice
        run: |
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
