name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Set up ssh-agent
      uses: yakuhzi/action-ssh-agent@v1
      with:
        public: ${{ secrets.SSH_PUBLIC_KEY }}
        private: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: actions/checkout@v1
    - name: pod install
      run: pod install
    - name: Run a multi-line script
      run: |
        for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
        xcodebuild -workspace The\ Guardian.xcworkspace -scheme The\ Guardian -configuration Release -derivedDataPath $HOME/The\ Guardian build
