name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: pod install
      run: pod install
    - name: Run a multi-line script
      run: |
        xcodebuild -project The Guardian.xcworkspace -scheme The Guardian -configuration Release -derivedDataPath $HOME/The Guardian build
