name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: pod install
      run: pod install
    - name: Run a multi-line script
      run: |
        sudo xcode-select -switch /Applications/Xcode_11.app
        xcodebuild -project Application.xcodeproj -scheme Application -configuration Release -derivedDataPath $HOME/Application build
